name: Build and Push Docker Image on Release

on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract release tag name
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Build and Push Docker Image
              run: |
                  docker build -t mariusbegby/cadence:${{ env.RELEASE_VERSION }} .
                  docker push mariusbegby/cadence:${{ env.RELEASE_VERSION }}
                  docker push mariusbegby/cadence:latest
