name: Release Notes PR

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v3
              with:
                  token: ${{ secrets.CUSTOM_TOKEN }}
                  release-type: node
                  package-name: release-please-action
                  changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Minor changes and bug fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
